#!/bin/sh /etc/rc.common

START=10
STOP=15
 
start() {        
        iptables -t mangle -I PREROUTING -i wwan0 -j TTL --ttl-inc 2
        iptables -t mangle -I POSTROUTING -o wwan0 -j TTL --ttl-inc 2
        ip6tables -t mangle -I PREROUTING ! -p icmpv6 -i wwan0 -j HL --hl-inc 2
        ip6tables -t mangle -I POSTROUTING ! -p icmpv6 -o wwan0 -j HL --hl-inc 2
}                 
 
stop() {          
        echo stop
        # commands to kill application 
}
